# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  config.vm.box = "base"
  # config.vm.box_url = "http://domain.com/path/to/above.box"
  # config.vm.boot_mode = :gui
  # config.vm.network :hostonly, "192.168.33.10"
  # config.vm.forward_port 80, 8080
  # config.vm.share_folder "v-data", "/vagrant_data", "../data"
  #
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "./"
    puppet.manifest_file  = "manifest.pp"
  end
end
