# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|


  config.vm.define :setupbox do |setupbox|
    setupbox.vm.box = "setupbox"
    # setupbox.vm.box_url = "http://domain.com/path/to/above.box"
    # setupbox.vm.boot_mode = :gui
    # setupbox.vm.network :hostonly, "192.168.33.10"
    # setupbox.vm.forward_port 80, 8080
    # setupbox.vm.share_folder "v-data", "/vagrant_data", "../data"
    #
    setupbox.vm.network :hostonly, "33.33.33.60"
    setupbox.ssh.forward_agent = true
    
    setupbox.vm.provision :puppet do |puppet|
      puppet.manifests_path = "./"
      puppet.manifest_file  = "manifest.pp"
      puppet.module_path = "../../modules"
      puppet.options = "--verbose --debug"
    end
  end
  
end
